### ISSUE TITLE
Invert C-Stick Option

### ISSUE THREAD

**Issue by ArgonUK** [FIX94/Nintendont#360]
Hi everyone,
I did some research about basic controls customization, and found out that there is no option to invert axis on the controllers. It could be quite annoying, as some games, like Super Mario Sunshine, doesn't offer option to invert axis and then you struggle with the controls through entire game.

Could the following option be added into Nintendont?

**Invert Control Stick X-axis       no/yes
Invert Control Stick Y-axis       no/yes
Invert C-Stick X-axis                no/yes
Invert C-Stick Y-axis                no/yes**

I normally use original GC controller and would very welcome such function. Meanwhile, could someone compile most recent nintendont with inverted C-Stick X-axis?
Similar functionality were requested already at
https://github.com/FIX94/Nintendont/issues/260

**Comment by missionfloyd** [comment]
For now, here's an ocarina code to invert C-stick x in super mario sunshine.

NTSC
```
GMSE01
Super Mario Sunshine

Invert Camera Rotation
04025050 FFE00850
04029204 FFE00890
```
PAL
```
GMSP01
Super Mario Sunshine

Invert Camera Rotation
04025108 FFE00850
040292BC FFE00890
```

**Comment by ArgonUK** [comment]
It is a work around I am currently using. A proper function implementation would be appreciated. There are quite a few more games that have similar camera control behavior and no patches available.

**Comment by mikedubbz** [comment]
I'd like for this to be possible as well, hitting L3 or R3 to make the c-stick inverted would be great.  Worms 3D suffers from having the aiming not inverted which in that game is truly counter intuitive.

**Comment by wazzusig** [comment]
I am interested in the "workaround" but wasn't really given context. What are the exact steps I need to take to do this? It's driving me crazy in super mario sunshine.

**Comment by ArgonUK** [comment]
@wazzusig 

You should use workaround cheat codes with Ocarina Cheat Engine as .gct codes. There are plenty tutorials on the internet, find one for the platform you are using.

**Comment by wazzusig** [comment]
@ArgonUK 

I found an invert ocarina code, but it doesn't seem to work on vwii usb loader (ocarina cheat enabled). My hunch is it was coded for regular wii nintendont and not sure if there is a translation. Could you direct me if you know a solution?

**Comment by HeIp** [comment]
how did you guys change the controls ? where is the guide ?

**Comment by ArgonUK** [comment]
@wazzusig @HeIp 
Hm, these ocarina codes should be universal.

A. I activated these codes, using USB Loader GX:
1. I downloaded available codes using loader for each game just to get game ID and overall structure right;
2. Removed them from downloaded "GAMEID".txt, pasted the relevant codes from this thread into GAMEID.txt;
3. enabled codes by creating GAMEID.gct;

B. Enabled cheats in Nintendont options
C. Launched game with "corrected" controls

P.S. I also suggest using proper widescreen Ocarina codes, rather than Nintendont integrated option for a proper widescreen hack.

**Comment by HeIp** [comment]
Im fairly new to this, @ArgonUK thank you for this reply, could you also supply the forum link as I am not all that too knowledgeable on what you said.

**Comment by ArgonUK** [comment]
@HeIp No Problem.

**Nintendont FAQ:**
https://gbatemp.net/threads/nintendont.349258/#NintendontCheats
FAQ is slightly obsolete, kenobiwii.bin is not required with a new version of nintendont.

**USB Loader GX Thread:**
https://gbatemp.net/threads/usb-loader-gx.149922/
I use this loader for .gct creation, since it shares the same cheat paths with nintendont.

**Comment by HeIp** [comment]
> 00d0 c0de 00d0 c0de 0402 5050 ffe0 0850
> 0402 9204 ffe0 0890 ff00 0000 0000 0000

Would you say that's the .gct file for the inverted c control for sunshine ?

**Comment by digglife** [comment]
I'm looking for the code for The Wind Waker the Japan Version(GZLJ01). There is a [thread](http://www.gc-forever.com/forums/viewtopic.php?f=38&t=2373&start=25#p35090) discussing about it but the code doesn't work. So it there a way for me to figure out the right address and value? Any online guide please?

**Comment by mistertoze** [comment]
There aren't cheats for all games that are lacking an Invert setting.

It would be great if Nintendont had two options, "Invert Y-Axis" and "Invert X-Axis".

Then whatever loader would set those on or off depending on the game.

**Comment by cucholix** [comment]
During GCN days inverted y axis was the standart, but it feels akwards nowaday :p, it would nice to have an universal option to invert the inverted Y C-Stick

**Comment by Exormeter** [comment]
To stop everyone with the PAL version the hassle to try: The Super Mario Sunshine code only works on with the NTSC-U version.

**Comment by Angelhpascual** [comment]
Is this code still working on NTSC? I’m crazy trining to change the camera movements on nintendont

**Comment by Exormeter** [comment]
Definitely working.

**Comment by Angelhpascual** [comment]
Thank you for your reply Exometer but I have a Wii U from EU coz I’m Spanish. Can I play this amazing game with inverted controllers on my Wii U pal? Thank you dude!

**Comment by carnage702** [comment]
nintendont is region free, doesnt matter if you play pal or ntsc isos doesnt make a diference.

**Comment by Exormeter** [comment]
Only the game version matters, I play it on a PAL Wii myself.

**Comment by Angelhpascual** [comment]
Thank you for your responses guys, you helping me so much to understand this new world for me. How can I load the cheats on my nintendont in my Wii U?. 
I put a .gct file with the GMSP01 with this gecko code that I found on internet “inverted camera for Mario sunshine for PAL” 
Maybe I did something wrong. If you can help me I will appreciate it! Thank you!

**Comment by FIX94** [comment]
...but thats not even for the PAL version of super mario sunshine, thats on this page:
http://www.gc-forever.com/forums/viewtopic.php?f=38&t=2138

**Comment by Angelhpascual** [comment]
Fix94 you are my hero. Now I’m playing Mario sunshine with invert controller

**Comment by Boomchil** [comment]
Hi. Can anoyone please share a gct file with only the invert c-stick for the PAL version (GMSP01) ?

I have tried everything but it always results in a black screen when I turn on cheats (it works perfectly with them off).

I have gathered the code in http://www.gc-forever.com/forums/viewtopic.php?f=38&t=2138, put them in http://geckocodes.org/index.php?c=GMSP01 to generate the proper gct file but with no luck.

I have also tried the method indicated here (https://gbatemp.net/threads/use-gamecube-cheats-with-nintendont-dios-mios-etc.313218/) and it still won't load.

And yes I load the good GMSP01 version of the game.

I am on a Wii U with the latest Nintendont version.

I really cannot find what I'm doing wrong so if anyone can help me that would be fantastic :).

Thanks

**Comment by TopTenTiger** [comment]
Here's the .gct file for inverting the y-stick horizontally for the NTSC-U version of Super Mario Sunshine. I'm using this on the Wii.

- Unzip [GMSE01.zip](https://github.com/FIX94/Nintendont/files/2664408/GMSE01.zip) and place GMSE01.gct in the games dir (where game.iso is located) on ur SD/USB
- Launch Nintendont and goto settings for this game
- Enable Cheat Codes and Native Controls
- Launch game and enjoy

**Comment by Dragonfir3** [comment]
> Hi. Can anoyone please share a gct file with only the invert c-stick for the PAL version (GMSP01) ?

The file for PAL version: [GMSP01.gct.zip](https://github.com/FIX94/Nintendont/files/2669082/GMSP01.gct.zip), with Inverted Camera Rotation (C-Stick) and F.L.U.D.D. Inverted Y Axis Control.

**Comment by Porroe** [comment]
THPS4, THUG1 and THUG2 would also benefit from this. Does anyone have a .gct file for those?

**Comment by mendagui** [comment]
I want to play Super Mario Sunshine with inverted camera and a PS3 controller (I don't have a GameCube controller). 

> Here's the .gct file for inverting the c-stick horizontally for the NTSC-U version of Super Mario Sunshine. I'm using this on the Wii.
> 
> * Unzip [GMSE01.zip](https://github.com/FIX94/Nintendont/files/2664408/GMSE01.zip) and place GMSE01.gct in the games dir (where game.iso is located) on ur SD/USB
> * Launch Nintendont and goto settings for this game
> * Enable Cheat Codes and Native Controls
> * Launch game and enjoy

I did this but my Wii froze everytime I turned my PS3 controller on. Then I realized that I have to enable Native Controls, so I asume I could only use this method with a GameCube controller.

Is there any way I could play this game with a PS3 controller and inverted right stick?

**Comment by Knatch78** [comment]
Someone has solved with problems Invert C-Stick ?
annoyed does not work with inverted C-Stick Super mario sunshine :(

**Comment by bobtiji** [comment]
No it's still pending. am still waiting

**Comment by carlosfilho-git** [comment]
Hi there... I've been researching this kind of stuff for my kid that loves Mario.... he's using a ps4 controller, with 'controllers'.

I'm sharing what worked for me... The game is loaded directly from nintendont, that is on a version from 2021... never tried loading on usb loader gx.. I've done as it follows:

1- Put 'controllers' folder into sd root so the controller will act like a ps4/ps3.... controller (jump on X instead of O...it can be changed if you want, but thats another subject))[controllers.zip](https://github.com/FIX94/Nintendont/files/10473088/controllers.zip)

2- Put 'sneek' folder into sd root to eneable cheats [sneek.zip](https://github.com/FIX94/Nintendont/files/10473090/sneek.zip)

3- The cheat code file .gct can be created on https://mariokartwii.com/gct/ if you have the code. Anyways here's the one i'm using:
[GMSE01.zip](https://github.com/FIX94/Nintendont/files/10473103/GMSE01.zip) it goes in the same folder where the game.iso file is. Change the name of the .gct file in case:
-GMSE01 = For American MKWii
-GMSP01 = For European/Australian (PAL) MKWii
-GMSJ01 = For Japanese MKWii
-GMSK01 = For Korean MKWii

4- Turn on nintendont, on settings eneable cheats, i thinks is the first option... after all of that just enjoy your game.

Good luck.

**Comment by kesterstudios** [comment]
Crazy how Nintendon't has been around for many years and still doesn't have an option for inverting the C Stick. Even Swiss has this option. Sure there are cheat codes for inverting the C Stick, but not every game has an existing code for this.
